<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Interface for classes that define processors for the samples.
 *
 * @package   tool_excimer
 * @author    Jason den Dulk <jasondendulk@catalyst-au.net>
 * @copyright 2022, Catalyst IT
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace tool_excimer;

/**
 * Interface for classes that define processors for the samples.
 *
 * A processor takes the samples generated by the profiler manager, and
 * creates the profile(s) to be saved to disk.
 *
 * @package   tool_excimer
 */
class processor {
    /** @var int */
    protected $minduration;

    /** @var sample_set */
    public $tasksampleset;

    /** @var sample_set */
    public $memoryusagesampleset;

    /** @var int */
    protected $samplingperiod;

    /** @var int */
    protected $samplelimit;

    /** @var int */
    protected $maxsamples;

    /** @var int */
    protected $logcount = 0;

    /** @var bool */
    protected static $alreadyprofiling = false;

    /** @var array */
    protected static $logs = [];

    /**
     * Construct the processor.
     */
    public function __construct() {
        // Preload config values to avoid DB access during processing. See manager::get_altconnection() for more information.
        $this->samplingperiod = script_metadata::get_sampling_period();
        $this->samplelimit = script_metadata::get_sample_limit();
        $this->maxsamples = script_metadata::get_max_samples();
    }

    /**
     * Doubling the sampling period when we reach the samples limit
     *
     * @param manager $manager
     */
    public function on_reach_limit(manager $manager) {
        $this->samplingperiod *= 2;
        // This will take effect the next time start() is called.
        $manager->get_profiler()->setPeriod($this->samplingperiod);
        $manager->get_profiler()->start();
    }

    /**
     * Gets the minimum duration required for a profile to be saved, as seconds.
     *
     * @return float
     */
    public function get_min_duration(): float {
        return $this->minduration;
    }
}
