<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace tool_excimer;

/**
 * Processor for web script profiling.
 *
 * Makes one profile per run, with partial saving if the script runs long enough.
 *
 * @package   tool_excimer
 * @author    Jason den Dulk <jasondendulk@catalyst-au.net>
 * @copyright 2022, Catalyst IT
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class web_processor extends processor {
    /** @var profile The profile object for the run. */
    protected $profile;

    /** @var bool */
    protected $partialsave;
    /** @var bool  */
    protected $hasoverlapped = false;

    /**
     * Construct the web processor.
     */
    public function __construct() {
        parent::__construct();
        $this->minduration = (float) get_config('tool_excimer', 'trigger_ms') / 1000.0;
        $this->partialsave = get_config('tool_excimer', 'enable_partial_save');
    }

    /**
     * Initialises the processor
     *
     * @param manager $manager The profiler manager object
     */
    public function init(manager $manager) {
        global $ME, $SCRIPT;
        // Record and set initial memory usage at this point.
        $memoryusage = memory_get_usage();
        $request = script_metadata::get_normalised_relative_script_path($ME, $SCRIPT);
        $starttime = (int) $manager->get_starttime();
        $this->tasksampleset = new sample_set($request, $starttime);

        // Add sampleset for memory usage - this sets the baseline for the profile.
        $this->memoryusagesampleset = new sample_set($request, $starttime);
        $this->memoryusagesampleset->add_sample(['sampleindex' => 0, 'value' => $memoryusage]);

        $this->profile = new profile();
        $this->profile->add_env($this->tasksampleset->name);
        $this->profile->set('created', $this->tasksampleset->starttime);

        if ($this->partialsave) {
            // The callback is triggered when the number of samples reach the maxsamples and when profiler is destroyed.
            $manager->get_profiler()->setFlushCallback(function ($log) use ($manager) {
                // Once overlapping has happened once, we prevent all future partial saving.
                if (!$this->hasoverlapped) {
                    $this->on_flush($log, $manager);
                }
            }, $this->maxsamples);
        }

        \core_shutdown_manager::register_function(
            function () use ($manager) {
                // The final on_flush is expected to be called if $this->partialsave.
                $manager->get_profiler()->stop();
                if (!$this->partialsave) {
                    $log = $manager->get_profiler()->flush();
                    $this->on_flush($log, $manager);
                }
                // Do the final profile process.
                $this->process($manager, true);
                page_group::record_fuzzy_counts($this->profile);
            }
        );
    }

    /**
     * Examines a sample generated by the profiler.
     *
     * The logic represents the following:
     *
     * If a sample is the first of a task, we create a task_samples instance, and add the sample.
     * As long as subsequent samples are in the same task, we keep adding them to task_samples.
     * When we get to a sample that is not in the same task, we process the task_samples and reset it.
     *
     * We then check for a new task with the current sample.
     *
     * @param \ExcimerLog $log
     * @param manager $manager
     */
    public function on_flush($log, manager $manager) {
        // We want to prevent overlapping of processing, so skip if an existing process is still executing.
        // The profile logs will be kept and processed the next time.
        self::$logs[] = $log;
        $this->logcount += $log->count();
        // Doubling sampling period if it reaches the limit.
        if ($this->partialsave && $this->logcount >= $this->samplelimit) {
            $this->on_reach_limit($manager);
            $this->logcount = $this->logcount - $this->samplelimit;
        }
        if (self::$alreadyprofiling) {
            $this->hasoverlapped = true;
            debugging('tool_excimer: starting web_processor::process when previous process has not yet finished');
            if ($log->count() < $this->samplelimit) {
                // This should never happen.
                debugging('tool_excimer: alreadyprofiling is true during final process.');
            }
            return;
        }
        self::$alreadyprofiling = true;
        foreach (self::$logs as $log) {
            $memoryusage = memory_get_usage();
            $this->tasksampleset->add_many_samples($log);
            $this->memoryusagesampleset->add_sample([
                'sampleindex' => $this->tasksampleset->total_added() - 1,
                'value' => $memoryusage,
            ]);
        }
        $this->process($manager);
        self::$logs = [];
        self::$alreadyprofiling = false;
    }

    /**
     * Processes stored samples to create a profile.
     *
     * @param manager $manager
     * @param bool $isfinal
     * @throws \dml_exception
     */
    public function process(manager $manager, $isfinal = false) {
        $current = microtime(true);
        $currentrusage = getrusage();
        $duration = $current - $manager->get_starttime();
        $this->profile->set('duration', $duration);
        $cpuduration = helper::get_rusage_timediff($manager->get_startrusage(), $currentrusage);
        $this->profile->set('usercpuduration', $cpuduration['user']);
        $this->profile->set('systemcpuduration', $cpuduration['system']);
        $this->profile->set('maxstackdepth', $this->tasksampleset->get_stack_depth());
        $reason = $manager->get_reasons($this->profile);
        if ($reason !== profile::REASON_NONE) {
            $this->profile->set('reason', $reason);
            $this->profile->set('finished', $isfinal ? (int)$current : 0);
            $this->profile->set('memoryusagedatad3', $this->memoryusagesampleset->samples);
            $this->profile->set('flamedatad3', flamed3_node::from_sample_set_samples($this->tasksampleset->samples));
            $this->profile->set('numsamples', count($this->tasksampleset->samples));
            $this->profile->set('numevents', $this->tasksampleset->count());
            $this->profile->set('samplerate', (int) (($duration * 1000) / $this->tasksampleset->count()));
            foreach (script_metadata::get_lock_info() as $field => $value) {
                $this->profile->set($field, $value);
            }
            $this->profile->save_record();
        }
    }
}
